In [2]:
import pandas as pd

df = pd.read_csv("../resources/contradictory-my-dear-watson/train.csv")

pd.set_option('display.max_columns', None)

df.head(5)

,id,premise,hypothesis,lang_abv,language,label
0,5130fd2cb5,and these comments were considered in formulat...,The rules developed in the interim were put to...,en,English,0
1,5b72532a0b,These are issues that we wrestle with in pract...,Practice groups are not permitted to work on t...,en,English,2
2,3931fbe82a,Des petites choses comme celles-là font une di...,J'essayais d'accomplir quelque chose.,fr,French,0
3,5622f0c60b,you know they can't really defend themselves l...,They can't defend themselves because of their ...,en,English,0
4,86aaa48b45,ในการเล่นบทบาทสมมุติก็เช่นกัน โอกาสที่จะได้แสด...,เด็กสามารถเห็นได้ว่าชาติพันธุ์แตกต่างกันอย่างไร,th,Thai,1

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12120 entries, 0 to 12119
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          12120 non-null  str
 1   premise     12120 non-null  str
 2   hypothesis  12120 non-null  str
 3   lang_abv    12120 non-null  str
 4   language    12120 non-null  str
 5   label       12120 non-null  int64
dtypes: int64(1), str(5)
memory usage: 568.3 KB

In [4]:
print(df.isnull().sum())

id            0
premise       0
hypothesis    0
lang_abv      0
language      0
label         0
dtype: int64

In [11]:
# get a generic sense for if the rows look corrupted for NA values
null_rows = df[df['keyword'].isnull()]
null_rows

,id,keyword,location,text,target
31,48,ablaze,Birmingham,@bbcmtd Wholesale Markets ablaze http://t.co/l...,1
32,49,ablaze,Est. September 2012 - Bristol,We always try to bring the heavy. #metal #RT h...,0
33,50,ablaze,AFRICA,#AFRICANBAZE: Breaking news:Nigeria flag set a...,1
34,52,ablaze,"Philadelphia, PA",Crying out for more! Set me ablaze,0
35,53,ablaze,"London, UK",On plus side LOOK AT THE SKY LAST NIGHT IT WAS...,0
...,...,...,...,...,...
7578,10830,wrecked,NaN,@jt_ruff23 @cameronhacker and I wrecked you both,0
7579,10831,wrecked,"Vancouver, Canada",Three days off from work and they've pretty mu...,0
7580,10832,wrecked,London,#FX #forex #trading Cramer: Iger's 3 words tha...,0
7581,10833,wrecked,Lincoln,@engineshed Great atmosphere at the British Li...,0
7582,10834,wrecked,NaN,Cramer: Iger's 3 words that wrecked Disney's s...,0

In [12]:
null_rows['target'].value_counts()

target
0    4323
1    3229
Name: count, dtype: int64

In [19]:
# how to replace null values?
print(df['clean_title'].nunique())
df['clean_title'].value_counts(dropna=False)

1

clean_title
Yes    167114
NaN     21419
Name: count, dtype: int64

In [21]:
df['fuel_type'].value_counts()

fuel_type
Gasoline          165940
Hybrid              6832
E85 Flex Fuel       5406
Diesel              3955
–                    781
Plug-In Hybrid       521
not supported         15
Name: count, dtype: int64

In [22]:
# correlation of numberic values with target column
df.corr(numeric_only=True)['price']

id           -0.000877
model_year    0.231795
milage       -0.283067
price         1.000000
Name: price, dtype: float64

In [24]:
# frequency count of vaues of non-numeric columns

cat_cols = df.select_dtypes(exclude='number').columns
print(type(cat_cols))
#cat_cols = cat_cols.drop(['PassengerId', 'Name', 'Cabin'])
# Print the value counts for each categorical column
for col in cat_cols:
    print(f"--- Frequency Count for Column: {col} ---")
    print(df[col].value_counts())
    print("\n")

<class 'pandas.Index'>
--- Frequency Count for Column: brand ---
brand
Ford             23088
Mercedes-Benz    19172
BMW              17028
Chevrolet        16335
Audi             10887
Porsche          10612
Land              9525
Toyota            8850
Lexus             8643
Jeep              6474
Cadillac          4674
RAM               4249
Nissan            3930
Tesla             3738
INFINITI          3276
GMC               3215
Dodge             3133
Mazda             2719
Kia               2497
Lincoln           2423
Subaru            2381
Acura             2282
Honda             2101
Hyundai           2045
Volkswagen        1765
Jaguar            1319
Bentley           1155
MINI              1064
Genesis            969
Buick              940
Maserati           939
Lamborghini        809
Chrysler           727
Volvo              723
Alfa               682
Rivian             590
Rolls-Royce        561
Mitsubishi         551
Pontiac            538
Hummer             520
Ferrari            359
McLaren            243
Aston              238
Saturn             148
Scion              120
Lucid               69
Mercury             57
Lotus               52
FIAT                44
Saab                22
Karma               17
Suzuki               8
Plymouth             7
Bugatti              7
Polestar             7
smart                3
Maybach              3
Name: count, dtype: int64


--- Frequency Count for Column: model ---
model
F-150 XLT                        2945
M3 Base                          2229
Camaro 2SS                       1709
M4 Base                          1622
Mustang GT Premium               1526
                                 ...
IONIQ Plug-In Hybrid SEL            2
X5 xDrive40e                        1
X5 3.0i                             1
XLR Base                            1
Integra w/A-Spec Tech Package       1
Name: count, Length: 1897, dtype: int64


--- Frequency Count for Column: fuel_type ---
fuel_type
Gasoline          165940
Hybrid              6832
E85 Flex Fuel       5406
Diesel              3955
–                    781
Plug-In Hybrid       521
not supported         15
Name: count, dtype: int64


--- Frequency Count for Column: engine ---
engine
355.0HP 5.3L 8 Cylinder Engine Gasoline Fuel           3462
240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel           2902
420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel           2841
2.0L I4 16V GDI DOHC Turbo                             2680
375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel          2451
                                                       ...
151.0HP 1.5L 4 Cylinder Engine Gas/Electric Hybrid        1
184.0HP 2.4L 4 Cylinder Engine Flex Fuel Capability       1
78.0HP 1.2L 3 Cylinder Engine Gasoline Fuel               1
139.0HP 1.6L 4 Cylinder Engine Plug-In Electric/Gas       1
313.0HP 2.0L 4 Cylinder Engine Plug-In Electric/Gas       1
Name: count, Length: 1117, dtype: int64


--- Frequency Count for Column: transmission ---
transmission
A/T                                                   49904
8-Speed A/T                                           20645
Transmission w/Dual Shift Mode                        19255
6-Speed A/T                                           18044
6-Speed M/T                                           11998
7-Speed A/T                                           11124
Automatic                                             10691
8-Speed Automatic                                      8431
10-Speed A/T                                           8044
9-Speed A/T                                            3866
5-Speed A/T                                            3217
10-Speed Automatic                                     3164
6-Speed Automatic                                      2799
4-Speed A/T                                            2546
5-Speed M/T                                            2409
9-Speed Automatic                                      2325
CVT Transmission                                       1990
1-Speed A/T                                            1869
M/T                                                    1179
7-Speed Automatic with Auto-Shift                      1172
Automatic CVT                                           829
8-Speed Automatic with Auto-Shift                       549
1-Speed Automatic                                       365
7-Speed M/T                                             355
6-Speed Manual                                          211
7-Speed Automatic                                       178
5-Speed Automatic                                       159
Transmission Overdrive Switch                           156
7-Speed Manual                                          151
6-Speed Automatic with Auto-Shift                       111
2                                                        91
–                                                        87
2-Speed A/T                                              71
Variable                                                 66
F                                                        65
4-Speed Automatic                                        48
10-Speed Automatic with Overdrive                        40
6 Speed Mt                                               37
9-Speed Automatic with Auto-Shift                        33
6-Speed Electronically Controlled Automatic with O       31
7-Speed                                                  29
8-Speed Manual                                           28
Manual                                                   27
6-Speed                                                  27
2-Speed Automatic                                        22
6 Speed At/Mt                                            20
7-Speed DCT Automatic                                    18
Single-Speed Fixed Gear                                  16
CVT-F                                                    15
8-SPEED AT                                               13
8-SPEED A/T                                               7
SCHEDULED FOR OR IN PRODUCTION                            6
Name: count, dtype: int64


--- Frequency Count for Column: ext_col ---
ext_col
Black                                 48658
White                                 43815
Gray                                  25293
Silver                                16995
Blue                                  14555
                                      ...
Granite Crystal Metallic Clearcoat        5
Blue Caelum                               5
GT SILVER                                 5
BLUE                                      3
Mango Tango Pearlcoat                     2
Name: count, Length: 319, dtype: int64


--- Frequency Count for Column: int_col ---
int_col
Black           107674
Beige            24495
Gray             21204
Brown             5810
Red               5145
                 ...
Nougat Brown         7
Classic Red          7
Cobalt Blue          6
WHITE                6
ORANGE               4
Name: count, Length: 156, dtype: int64


--- Frequency Count for Column: accident ---
accident
None reported                             144514
At least 1 accident or damage reported     41567
Name: count, dtype: int64


--- Frequency Count for Column: clean_title ---
clean_title
Yes    167114
Name: count, dtype: int64

In [15]:

pd.crosstab(df['CryoSleep'], df['Transported'])

Transported     0     1
CryoSleep
False        3650  1789
True          554  2483