In [1]:
import pandas as pd

df = pd.read_csv("resources/playground-series-s6e5/train.csv")

pd.set_option('display.max_columns', None)

df.head(5)

,id,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,0,D109,HARD,Canadian Grand Prix,2022,0,50,2,39.0,8,78.491,-7.564,21.019,0.714286,5.0,1.0
1,1,D086,HARD,Dutch Grand Prix,2025,1,27,2,7.0,4,75.095,-32.617,-223.207,0.346154,-3.0,0.0
2,2,ZON,HARD,Austrian Grand Prix,2022,0,59,3,22.0,13,70.945,-7.540,-100.529,0.819444,3.0,1.0
3,3,SPE,MEDIUM,Pre-Season Testing,2023,0,2,1,2.0,7,94.361,-7.324,-7.324,0.076923,0.0,0.0
4,4,D019,HARD,Azerbaijan Grand Prix,2022,1,26,3,6.0,2,107.878,8.965,-14.139,0.361111,3.0,0.0

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 439140 entries, 0 to 439139
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      439140 non-null  int64
 1   Driver                  439140 non-null  str
 2   Compound                439140 non-null  str
 3   Race                    439140 non-null  str
 4   Year                    439140 non-null  int64
 5   PitStop                 439140 non-null  int64
 6   LapNumber               439140 non-null  int64
 7   Stint                   439140 non-null  int64
 8   TyreLife                439140 non-null  float64
 9   Position                439140 non-null  int64
 10  LapTime (s)             439140 non-null  float64
 11  LapTime_Delta           439140 non-null  float64
 12  Cumulative_Degradation  439140 non-null  float64
 13  RaceProgress            439140 non-null  float64
 14  Position_Change         439140 non-null  float64
 15  PitNextLap              439140 non-null  float64
dtypes: float64(7), int64(6), str(3)
memory usage: 53.6 MB

In [3]:
print(df.isnull().sum())

id                        0
Driver                    0
Compound                  0
Race                      0
Year                      0
PitStop                   0
LapNumber                 0
Stint                     0
TyreLife                  0
Position                  0
LapTime (s)               0
LapTime_Delta             0
Cumulative_Degradation    0
RaceProgress              0
Position_Change           0
PitNextLap                0
dtype: int64

In [5]:
df['PitNextLap'].value_counts()

PitNextLap
0.0    351759
1.0     87381
Name: count, dtype: int64

In [22]:
# correlation of numberic values with target column
df.corr(numeric_only=True)['price']

id           -0.000877
model_year    0.231795
milage       -0.283067
price         1.000000
Name: price, dtype: float64

In [4]:
# frequency count of vaues of non-numeric columns

cat_cols = df.select_dtypes(exclude='number').columns
print(type(cat_cols))
#cat_cols = cat_cols.drop(['PassengerId', 'Name', 'Cabin'])
# Print the value counts for each categorical column
for col in cat_cols:
    print(f"--- Frequency Count for Column: {col} ---")
    print(df[col].value_counts())
    print("\n")

<class 'pandas.Index'>
--- Frequency Count for Column: Driver ---
Driver
MAS     1682
RAI     1669
BAR     1656
BUT     1655
FIS     1651
        ...
D711       1
D755       1
D731       1
D716       1
D714       1
Name: count, Length: 887, dtype: int64


--- Frequency Count for Column: Compound ---
Compound
MEDIUM          211141
HARD            170518
SOFT             38744
INTERMEDIATE     17382
WET               1355
Name: count, dtype: int64


--- Frequency Count for Column: Race ---
Race
Dutch Grand Prix             24462
Mexico City Grand Prix       23672
Pre-Season Testing           22492
Hungarian Grand Prix         22481
Monaco Grand Prix            21539
Canadian Grand Prix          21416
Austrian Grand Prix          21223
Spanish Grand Prix           20483
Italian Grand Prix           19854
Bahrain Grand Prix           19535
Singapore Grand Prix         18960
Miami Grand Prix             18860
Australian Grand Prix        18406
Saudi Arabian Grand Prix     18111
United States Grand Prix     18045
Abu Dhabi Grand Prix         16427
Emilia Romagna Grand Prix    15483
British Grand Prix           15383
Qatar Grand Prix             13817
Japanese Grand Prix          12891
Las Vegas Grand Prix         12479
Azerbaijan Grand Prix        12126
São Paulo Grand Prix         11497
Belgian Grand Prix            9002
Chinese Grand Prix            7311
French Grand Prix             3185
Name: count, dtype: int64

In [15]:

pd.crosstab(df['CryoSleep'], df['Transported'])

Transported     0     1
CryoSleep
False        3650  1789
True          554  2483