In [2]:
import pandas as pd
df = pd.read_csv("../resources/spaceship-titanic/train.csv")

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
df.head(5)

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   str
 1   HomePlanet    8492 non-null   str
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   str
 4   Destination   8511 non-null   str
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   str
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(2), str(5)
memory usage: 891.5+ KB

In [5]:
print(df.isnull().sum())

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [43]:
null_rows = df[df['Age'].isnull()]

In [46]:
null_rows

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
50,0052_01,Earth,False,G/6/S,TRAPPIST-1e,NaN,False,4.0,0.0,2.0,4683.0,0.0,Elaney Hubbarton,0
64,0068_01,Mars,False,E/4/S,TRAPPIST-1e,NaN,False,793.0,0.0,2.0,253.0,0.0,Cinst Binie,0
137,0149_01,Earth,True,G/27/S,55 Cancri e,NaN,False,0.0,0.0,0.0,0.0,0.0,Billya Hubbarrison,1
181,0202_02,Europa,False,A/2/P,55 Cancri e,NaN,False,0.0,2433.0,NaN,878.0,443.0,Vegas Embleng,1
184,0206_01,Europa,False,C/9/S,55 Cancri e,NaN,False,2.0,1720.0,12.0,1125.0,122.0,Nuson Brugashed,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8274,8835_01,Earth,True,G/1425/S,TRAPPIST-1e,NaN,False,0.0,0.0,0.0,0.0,0.0,Shalle Bartines,0
8301,8862_03,Europa,True,C/329/S,TRAPPIST-1e,NaN,False,0.0,0.0,0.0,0.0,0.0,Alchib Myling,1
8374,8956_04,Earth,False,G/1453/P,TRAPPIST-1e,NaN,False,194.0,1.0,10.0,629.0,0.0,Krisa Bonnondry,0
8407,8988_01,Earth,True,G/1448/S,TRAPPIST-1e,NaN,False,0.0,0.0,0.0,0.0,0.0,Maen Fowlesterez,1
8557,9136_01,Earth,False,G/1471/S,TRAPPIST-1e,NaN,False,6.0,0.0,0.0,800.0,3.0,Sall Hestes,0

In [17]:
df.corr(numeric_only=True)

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
Age,1.000000,0.068723,0.130421,0.033133,0.123970,0.101007,-0.075026
RoomService,0.068723,1.000000,-0.015889,0.054480,0.010080,-0.019581,-0.244611
FoodCourt,0.130421,-0.015889,1.000000,-0.014228,0.221891,0.227995,0.046566
ShoppingMall,0.033133,0.054480,-0.014228,1.000000,0.013879,-0.007322,0.010141
Spa,0.123970,0.010080,0.221891,0.013879,1.000000,0.153821,-0.221131
VRDeck,0.101007,-0.019581,0.227995,-0.007322,0.153821,1.000000,-0.207075
Transported,-0.075026,-0.244611,0.046566,0.010141,-0.221131,-0.207075,1.000000

In [18]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Transported'] = le.fit_transform(df['Transported'])

In [19]:
df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,0
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,1
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,0
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,0
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,1

In [20]:
df.corr(numeric_only=True)['Transported']

Age            -0.075026
RoomService    -0.244611
FoodCourt       0.046566
ShoppingMall    0.010141
Spa            -0.221131
VRDeck         -0.207075
Transported     1.000000
Name: Transported, dtype: float64

In [21]:
non_numeric_cols = df.select_dtypes(exclude='number')

print(non_numeric_cols.nunique())

PassengerId    8693
HomePlanet        3
CryoSleep         2
Cabin          6560
Destination       3
VIP               2
Name           8473
dtype: int64

In [35]:
cat_cols = df.select_dtypes(include=['object', 'category']).columns
print(type(cat_cols))
cat_cols = cat_cols.drop(['PassengerId', 'Name', 'Cabin'])
# Print the value counts for each categorical column
for col in cat_cols:
    print(f"--- Frequency Count for Column: {col} ---")
    print(df[col].value_counts())
    print("\n")

<class 'pandas.Index'>
--- Frequency Count for Column: HomePlanet ---
HomePlanet
Earth     4602
Europa    2131
Mars      1759
Name: count, dtype: int64


--- Frequency Count for Column: CryoSleep ---
CryoSleep
False    5439
True     3037
Name: count, dtype: int64


--- Frequency Count for Column: Destination ---
Destination
TRAPPIST-1e      5915
55 Cancri e      1800
PSO J318.5-22     796
Name: count, dtype: int64


--- Frequency Count for Column: VIP ---
VIP
False    8291
True      199
Name: count, dtype: int64

/tmp/ipykernel_16666/2351766728.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include=['object', 'category']).columns

In [53]:
pd.set_option('display.max_rows', None)

import numpy as np
(df['Age'].value_counts().sort_index())

Age
0.0     178
1.0      67
2.0      75
3.0      75
4.0      71
5.0      33
6.0      40
7.0      52
8.0      46
9.0      42
10.0     39
11.0     47
12.0     41
13.0    141
14.0    138
15.0    155
16.0    147
17.0    158
18.0    320
19.0    293
20.0    277
21.0    311
22.0    291
23.0    292
24.0    324
25.0    243
26.0    268
27.0    259
28.0    267
29.0    230
30.0    183
31.0    202
32.0    199
33.0    178
34.0    148
35.0    171
36.0    178
37.0    177
38.0    161
39.0    138
40.0    128
41.0    129
42.0    119
43.0    128
44.0    115
45.0     89
46.0     97
47.0     88
48.0     72
49.0     83
50.0     74
51.0     59
52.0     52
53.0     61
54.0     67
55.0     68
56.0     48
57.0     46
58.0     47
59.0     35
60.0     34
61.0     32
62.0     26
63.0     26
64.0     29
65.0     23
66.0      7
67.0     13
68.0     12
69.0      6
70.0      9
71.0      7
72.0      4
73.0      7
74.0      5
75.0      4
76.0      2
77.0      2
78.0      3
79.0      3
Name: count, dtype: int64

In [55]:
pd.crosstab(df['Name'], df['Transported'])

Transported         0  1
Name
Aard Curle          1  0
Aarjel Jaff         1  0
Aarjel Rhuba        1  0
Aark Ches           1  0
Aark Homin          0  1
Aarone Batestonley  0  1
Aarone Burryerson   0  1
Aarone Castannison  0  1
Aarone Fowlaney     1  0
Aarone Hoppers      1  0
Aarone Lewintos     1  0
Aarone Monroellynn  1  0
Aarone Sweett       0  1
Aars Pare           0  1
Acceleb Rimplighty  0  1
Acceleb Unrent      0  1
Achah Cassiding     1  0
Achah Stpingepid    0  1
Achbah Emetillove   1  0
Achbah Fansty       0  1
Achbah Fueling      1  0
Achib Heedry        0  1
Achib Ingascomet    0  1
Achib Pirejus       0  1
Achib Unteckery     0  1
Achira Capplid      0  1
Achira Reewerpic    1  0
Achira Uncionted    1  0
Achira Unhaftimle   1  0
Achiram Ainatint    0  1
Achiram Prefule     0  1
Achiram Turtertive  0  1
Achium Alenter      0  1
Achium Entratable   1  0
Achium Inderad      1  0
Achium Pokematic    0  1
Achyon Nalanet      0  1
Achyon Obedaming    1  0
Achyon Ranaly       0  1
Acraban Conamminal  1  0
Acrabih Droning     0  1
Acrabih Openduave   0  1
Acrabik Hoorherve   0  1
Acrabik Lendly      0  1
Acruxon Discuous    0  1
Acruxon Mirinanty   0  1
Acruxon Susent      0  1
Acruxon Swirring    0  1
Acruxon Unregul     0  1
Adamie Benney       0  1
Adamie Ingston      1  0
Adamie Leonzaley    0  1
Adamie Trerady      0  1
Adammy Coolerson    1  0
Adammy Hinglendez   1  0
Adammy Whitakers    0  1
Adamy Dayers        0  1
Adamy Hestes        1  0
Adamy Willy         1  0
Adamy Wolferton     1  0
Adanne Mejiaddox    1  0
Adanne Mosepherry   1  0
Adanne Rilley       0  1
Adanne Robley       0  1
Adanne Wartyson     0  1
Adharan Briouse     0  1
Adharan Greded      0  1
Adria Bakericks     1  0
Adria Cardners      0  1
Adria Cookentaney   0  1
Adrie Cochrisons    0  1
Adrie Dyers         1  0
Adrie Flemaney      0  1
Adrie Rodger        0  1
Adrie Thonyderson   1  0
Adriet Combson      0  1
Adriet Drakeekss    1  0
Adriet Hughriend    1  0
Adriet Kerristicey  0  1
Adriet Kramosley    1  0
Adriet Moodman      1  0
Adriet Valezaley    0  1
Agnesa Baldson      0  1
Agnesa Cainghannon  1  0
Agnesa Hickson      0  1
Agnesa Loway        1  0
Agnesa Olshaffey    0  1
Ainkard Amonysidle  0  1
Ainkard Calian      0  1
Ainkard Crakete     1  0
Ainkard Fanseld     1  0
Ainkard Folumorly   0  1
Ainkard Seflock     0  1
Ainkard Spandisket  1  0
Aino Chpeng         0  1
Aino Ineysive       0  1
Aino Sloweber       0  1
Ainon Conachets     1  0
Ainons Unkcatted    0  1
Ainor Fuelisent     1  0
Ainor Ingetrody     1  0
Ainoxa Alindiveng   0  1
Ainoxa Plattering   0  1
Ainoxa Preeldy      0  1
Ainoxa Scerodbox    0  1
Alam Iderinelay     1  0
Alam Lansuffle      0  1
Alamin Obsentork    1  0
Alancy Collinson    0  1
Alancy Flemaney     0  1
Alancy Gouldensen   1  0
Alancy Mcbritts     0  1
Alancy Mcgoway      1  0
Alancy Morez        0  1
Alancy Santry       0  1
Alar Alenter        0  1
Alar Exible         1  0
Alar Quelfly        1  0
Alar Tionstious     0  1
Alaratz Aloubtled   0  1
Alarion Swingse     0  1
Alark Eguing        1  0
Alark Noxiong       0  1
Alark Stingive      1  0
Alark Stivelte      1  0
Alark Wincer        0  1
Alarkab Aneter      0  1
Alarkab Mirinanty   1  0
Alarkab Reewerpic   0  1
Alarmus Modent      0  1
Alaron Holiabler    0  1
Alaron Obedaming    0  1
Alas Dischod        1  0
Alaslon Craleve     0  1
Alasmon Dischod     0  1
Alasmon Idercaling  1  0
Alasmon Meteet      0  1
Alasmon Secont      0  1
Alasmon Stiven      1  0
Alasym Bootty       1  0
Alasym Couresteer   0  1
Alathim Suasharic   1  0
Alathim Tabloory    1  0
Alathim Waring      1  0
Alatik Disheract    0  1
Alaton Mornaned     1  0
Alaton Trupistic    0  1
Alatrin Inghting    0  1
Alatrin Sprender    0  1
Alatrin Trallect    0  1
Alatrix Regmansidy  0  1
Alatrix Sometery    1  0
Alatrix Unfile      0  1
Alatrix Volloor     0  1
Alballa Boltund     0  1
Alballa Brailidy    0  1
Alballa Cracionfic  1  0
Alber Carpentley    1  0
Alber Corman        1  0
Alber Kerristicey   0  1
Alber Lopelases     1  0
Alber Puckenton     1  0
Alchib Myling       0  1
Alchird Apenelexy   1  0
Alchium Fictful     1  0
Alchium Ousious     1  0
Alchium Ressighty   0  1
Alchium Stranbeate  0  1
Alchium Unteckery   0  1
Alcorab Myling      0  1
Alcorab Suptive     0  1
Alcoran Clugeammy   1  0
Alcoran Distured    0  1
Alcoran Sysilstict  1  0
Alcorix Fanseld     0  1
Alcorix Scoudelle   0  1
Alcorix Spistory    1  0
Alcorix Unressind   1  0
Alcorux Bealvewd    1  0
Alcyon Brathful     0  1
Alcyon Hariourcal   0  1
Aldah Coustive      0  1
Aldah Healted       0  1
Aldah Honchoe       1  0
Aldeba Ainserfle    1  0
Aldeba Bootious     1  0
Aldeba Tionstious   1  0
Aldebah Gealably    0  1
Aldebah Ingwhed     0  1
Aldera Glisormal    0  1
Aldera Sprender     1  0
Aldera Supred       0  1
Aldera Wasterivel   0  1
Alderak Balightal   0  1
Alderak Nalanet     0  1
Alderak Platch      0  1
Alderak Wassird     0  1
Aldhib Diabysid     1  0
Aldhib Gulcepusy    0  1
Aldhib Mallisly     0  1
Aldibah Baleful     1  0
Aldibah Contery     1  0
Aldibah Mostedry    0  1
Aldibah Netshaless  1  0
Aldibi Dinsprody    1  0
Aldibi Frablerly    1  0
Aldun Clugeadry     1  0
Aldun Fanseld       0  1
Aldun Ricete        1  0
Aldun Taptiritty    0  1
Aldun Venticable    0  1
Aldun Wassird       0  1
Aldus Stradick      0  1
Alduson Oilpuring   1  0
Alduson Subateful   0  1
Ale Alberts         0  1
Ale Booneid         0  1
Ale Butty           0  1
Ale Casonston       1  0
Ale Kin             1  0
Ale Mclarseney      0  1
Ale Morrencis       1  0
Ale Pert            1  0
Ale Shpie           1  0
Ale Start           1  0
Aleen Hayertez      1  0
Aleen Sancasey      1  0
Aleen Sykess        1  0
Aleen Traverdy      1  0
Alendy Fryersonis   1  0
Alendy Llonovancis  1  0
Alendy Mclardson    1  0
Alendy Mondsey      1  0
Alendy Parsoney     0  1
Alendy Scottuez     0  1
Alendy Stannondez   0  1
Alendy Wardendez    0  1
Alendy Wolferguson  0  1
Alene Ellson        0  1
Alene Gibbsonton    1  0
Aleroy Bushins      1  0
Aleroy Cartz        1  0
Aleroy Gaineyerson  1  0
Aleroy Pentss       1  0
Ales Cha            0  1
Alex Berle          0  1
Aleys Creke         1  0
Alfrey Bucklandez   0  1
Alfrey Corman       0  1
Alfrey Santry       0  1
Alfrey Sarios       1  0
Alfrey Shieldson    1  0
Algedia Unaasor     1  0
Algenif Maxled      1  0
Algenif Oillepint   1  0
Algeno Conablese    0  1
Algeno Listive      0  1
Algeno Suasharic    1  0
Algiedi Cassiding   0  1
Algor Efulows       0  1
Algor Excialing     0  1
Algor Paterpad      0  1
Algor Sersocatic    0  1
Algork Amblereld    1  0
Algork Diateous     0  1
Algork Honatte      0  1
Algrafi Heedry      0  1
Alhail Cabraseed    1  0
Alhail Drelcate     0  1
Alhail Fulatorly    0  1
Alhail Mormonized   0  1
Alhail Stioutody    0  1
Alhain Graciansus   1  0
Alhaino Honatte     1  0
Alhaino Rewmid      1  0
Alhaino Sparsaxle   0  1
Alhair Inderly      1  0
Alhair Poselfle     1  0
Alhaula Inesely     0  1
Alhenah Ciplanke    0  1
Alhenah Suptive     0  1
Alheneb Emoted      0  1
Alheneb Unpasine    0  1
Aliakan Dister      0  1
Alicey Franankson   0  1
Alicey Wolferguson  1  0
Alie Grahangory     0  1
Aliedy Carrishley   1  0
Aliedy Cleman       1  0
Aliedy Hurchanney   0  1
Aliedy Jacostaney   0  1
Aliedy Oneiles      1  0
Aliedy Yanton       1  0
Aliey Chanash       1  0
Aliey Clemondsey    0  1
Aliey Leetersoney   1  0
Alik Spedlinale     1  0
Alik Spirfuent      1  0
Alino Ingent        0  1
Alino Namsheary     1  0
Alinon Sernator     1  0
Alkaida Distured    0  1
Alkeson Asticit     1  0
Alkeson Exnutch     1  0
Alkurak Dressink    0  1
All Brookes         1  0
All Buckson         0  1
All Curle           1  0
All Harta           1  0
All Leonzaley       0  1
All Pittler         1  0
All Sweett          1  0
All Wolferton       1  0
Allara Cainghannon  1  0
Allara Llovers      1  0
Allara Thomason     1  0
Allena Blacks       1  0
Allena Currisones   1  0
Allena Daviddley    1  0
Allena Hoppernardy  0  1
Allena Litthews     1  0
Allena Sellahaney   1  0
Allena Sullones     1  0
Allene Balley       1  0
Allene Belley       1  0
Allene Cartyernan   0  1
Allene Douglasen    0  1
Allene Hardonald    0  1
Allene Loverthyo    1  0
Allene Mccarveymon  1  0
Allene Noeley       1  0
Allene Warrishales  1  0
Alles Gene          0  1
Alley Brantuarez    1  0
Alley Briggston     0  1
Alley Micknightt    0  1
Allia Barris        1  0
Allia Bartines      0  1
Allie Smalls        0  1
Allie Willynnedy    0  1
Allift Flé          0  1
Allift Parté        0  1
Allota Fincy        0  1
Allots Knike        0  1
Allots Pota         1  0
Alls Birte          1  0
Alls Nutty          1  0
Alls Peane          0  1
Ally Bartines       0  1
Ally Mcintons       0  1
Ally Sterreray      1  0
Ally Thonyderson    1  0
Allyn Bonnondry     1  0
Allyn Horthy        1  0
Allyn Olivasquez    1  0
Allyn Simpsonks     1  0
Allyny Burchard     1  0
Allyny Ewiseston    1  0
Almara Currisones   0  1
Almara Delazarson   0  1
Almara Dickman      0  1
Almara Hickerson    1  0
Almara Sweenez      1  0
Almara Whitakers    0  1
Almary Brantuarez   1  0
Almary Gordanieves  1  0
Almary Sancasey     1  0
Almary Willangsey   0  1
Almelik Conable     0  1
Almino Earmeter     1  0
Almino Obsentork    1  0
Almino Rotter       1  0
Almino Slable       0  1
Almone Bost         1  0
Almone Kraie        0  1
Almone Prine        1  0
Almone Raste        1  0
Almone Sté          1  0
Alpha Amonsmane     1  0
Alpha Frolestty     0  1
Alpha Mosteraked    1  0
Alpha Stiviorad     0  1
Alphact Frakepeed   0  1
Alphact Gealter     0  1
Alphact Inderad     0  1
Alphact Meteet      0  1
Alphact Reedall     0  1
Alphah Cousel       0  1
Alphah Cratrave     0  1
Alphah Neceriont    1  0
Alphah Praded       0  1
Alphah Pumbody      0  1
Alphah Reelest      1  0
Alphah Wirdley      1  0
Alphein Igmable     0  1
Alraia Voliat       1  0
Alraiam Gocent      1  0
Alraid Valing       0  1
Alraida Ametic      0  1
Alraida Dingauge    1  0
Alraida Purellliss  0  1
Alraida Trattle     0  1
Alrain Unsible      1  0
Alrair Bealvewd     0  1
Alrair Taptiritty   0  1
Alrair Unhearfus    1  0
Alrairk Ambleetive  0  1
Alrairk Maxled      1  0
Alrairk Perable     0  1
Alrairk Proorbeng   0  1
Alrairk Veriedeezy  1  0
Alrais Fordulgaug   0  1
Alrais Modent       0  1
Alrais Pleele       0  1
Alraium Disivering  1  1
Alraium Syncepul    1  0
Alraixa Ainserfle   1  0
Alraixa Graciansus  0  1
Alrak Unative       1  0
Alrak Witeronfus    0  1
Alrakan Aivering    1  0
Alrakan Apedishaft  1  0
Alrakan Scoudelle   1  0
Alramak Listive     0  1
Alramak Prearright  0  1
Alramak Stiven      0  1
Alramix Myling      0  1
Alramix Secont      1  0
Alramix Swinvul     0  1
Alsafik Fouseding   0  1
Alsha Dynigic       1  0
Alsha Geneltic      0  1
Alsha Gocent        0  1
Alsham Irintious    0  1
Alsham Volloor      0  1
Alsuud Ressing      0  1
Altaira Unative     0  1
Altairk Folumorly   1  0
Altairk Heermy      1  0
Altan Mallisly      1  0
Altan Pernised      1  0
Altan Spandisket    0  1
Altanin Barmant     1  0
Altanin Dedometeel  0  1
Altanin Praded      1  0
Altanin Switud      0  1
Altar Clugete       1  0
Altar Freednal      0  1
Altara Bruthydre    1  0
Altara Openduave    0  1
Altara Pretive      0  1
Altara Righturter   1  0
Altara Stioutody    0  1
Altardr Flatic      0  1
Altardr Mosteraked  0  1
Altares Ancontaked  0  1
Altares Persed      0  1
Altark Susent       1  0
Alteron Emetillove  0  1
Aludram Dectory     0  1
Aludram Platch      1  0
Alurope Watuald     0  1
Alurops Clinarfork  1  0
Alurops Pringry     0  1
Alus Harte          1  0
Alus Upead          0  1
Alvia Barbes        0  1
Alvia Daviddley     1  0
Alvia Jacostaney    1  0
Alvia Shawforden    1  0
Alvira Cleachrand   0  1
Alvira Foxter       1  0
Alvira Miranciash   1  0
Alvira Potterry     0  1
Alvira Rostarks     0  1
Alwaide Bagetvable  1  0
Alwaide Sometery    0  1
Alyadum Barmant     0  1
Alyat Oidederval    0  1
Alyat Stingive      0  1
Alyatik Ratorring   0  1
Alzird Distured     1  0
Alzird Gented       0  1
Alzird Prighty      0  1
Alzirk Aneetle      0  1
Amandy Hessey       1  0
Amandy Hultz        0  1
Amandy Munozanson   1  0
Ambert Ericksonga   0  1
Ambert Guezaley     1  0
Ambert Sellentry    1  0
Ambert Tranciams    0  1
Ambert Weaves       1  0
Ambert Woody        0  1
Amela Hurchanney    1  0
Amela Hurles        0  1
Amela Moodson       0  1
Amela Starkers      1  0
Amyra Hersons       1  0
Amyra Kirks         0  1
Anack Deeke         0  1
Anack Trad          1  0
Anae Oconley        1  0
Anae Sancasey       1  0
Anae Vaught         0  1
Anakes Canie        0  1
Analdy Alberts      0  1
Analdy Bardina      1  0
Analdy Bartez       1  0
Analdy Bucknersony  1  0
Analdy Farmonrada   1  0
Anamse Backe        0  1
Anamse Cha          0  1
Anamse Dal          1  0
Anch Opie           1  0
Anch Perta          1  0
Anchab Arible       0  1
Ancham Heateele     0  1
Ancham Spandisket   0  1
Anchib Crakete      0  1
Anchib Repumparte   1  0
Anchira Nateansive  1  0
Anchira Spassive    1  0
Anchird Boderbint   0  1
Anchird Exnutch     0  1
Anchird Rotter      1  0
Anchird Witeronfus  1  0
Anda Cartez         1  0
Anda Flemaney       0  1
Anda Fryan          0  1
Anda Gregordy       1  0
Anda Jimes          0  1
Anda Lardy          0  1
Anda Mcfaddennon    0  1
Andace Kinson       1  0
Andace Thonyderson  1  0
Andan Alentonway    1  0
Andan Estron        1  0
Andan Handertiz     1  0
Andan Stannondez    1  0
Andan Wartyson      1  0
Andary Hurchez      1  0
Andary Toddleton    0  1
Andary Wilderssen   1  0
Andice Dickley      0  1
Andice Maystuarey   1  0
Andice Tranciams    1  0
Andie Burnewman     1  0
Andie Campson       0  1
Andie Gambs         0  1
Andie Mirezavis     0  1
Andie Rices         0  1
Andie Wolfernan     1  0
Andine Hales        1  0
Andine Mcneiley     1  0
Andine Mcphernard   1  0
Andona Beston       0  1
Andona Winsley      1  0
Andra Cohendright   0  1
Andra Drakeekss     0  1
Andra Medington     1  0
Andrey Cooperkins   0  1
Andrey Farmonrada   1  0
Andrey Fisherry     0  1
Andrey Mcgowaymond  0  1
Andrey Navages      0  1
Andrey Norrison     1  0
Andyn Alvasquez     1  0
Andyn Ballocks      0  1
Andyn Brenney       1  0
Andyn Humphreyes    0  1
Andyn Ryanga        0  1
Ane Nan             1  0
Ane Read            0  1
Anes Lake           0  1
Angars Blate        1  0
Ankaan Reming       0  1
Ankaan String       0  1
Ankab Fueling       1  0
Ankab Speating      1  0
Ankabih Derterval   0  1
Ankabih Dightent    1  0
Ankabih Idivent     0  1
Ankabih Tradve      0  1
Ankabit Holatirint  0  1
Ankabit Parbleake   0  1
Ankalik Cylistrand  1  0
Ankalik Nateansive  0  2
Ankark Crakenecal   1  0
Ankark Persed       1  0
Annah Cookson       1  0
Annah Gilleyons     0  1
Annah Josey         0  1
Annah Morsentley    0  1
Annah Santry        1  0
Annaha Barnoldeney  0  1
Annaha Hahnstoneal  1  0
Annaha Harverez     0  1
Annaha Rivanseney   0  1
Annams Mellé        0  1
Annard Armstromez   1  0
Annard Ashipeck     0  1
Annard Bryants      1  0
Annard Charryerry   1  0
Annard Garnes       1  0
Annard Jacostaffey  1  0
Annard Merce        1  0
Annard Scottuez     0  1
Annez Bellarkerd    1  0
Annez Chapmaney     0  1
Annez Parrett       1  0
Annez Webstenson    0  1
Anniey Baketton     1  0
Anniey Gallenry     0  1
Anniey Hortez       1  0
Anniey Mccarry      1  0
Annon Anthompson    0  1
Annon Cartiz        0  1
Annon Knoxtones     0  1
Annon Moodsey       0  1
Annon Solon         1  0
Annon Thorney       0  1
Anny Bellarkerd     0  1
Anny Jeffey         1  0
Anny Mallerez       1  0
Anny Tersony        1  0
Annya Blange        1  0
Annya Frazie        1  0
Annya Patthews      1  0
Annya Talls         0  1
Annya Willy         1  0
Antak Bootty        1  0
Anthia Briggins     1  0
Anthia Mcbriddley   1  0
Anthia Savaraldez   0  1
Anthia Solon        1  0
Anthia Willangsey   0  1
Antino Wassird      1  0
Antinon Imparmle    1  0
Antinon Inging      0  1
Antinon Patoetic    0  1
Antinon Plaricit    0  1
Antinon Whifounrew  0  1
Antitak Goortedant  0  1
Antitak Scerodbox   0  1
Anton Booness       1  0
Anton Caljoiry      1  0
Anton Pearsalason   1  0
Anton Vantonson     0  1
Anton Woody         2  0
Antone Cardner      0  1
Antone Fielson      1  0
Antone Leton        0  1
Antone Mayods       1  0
Antone Sellentry    1  0
Antonon Clugeadry   0  1
Antony Flynnis      1  0
Antony Frederry     1  0
Antony Hersons      1  0
Antony Jacostaney   0  1
Antony Morrencis    1  0
Antony Singtons     0  1
Ants Fone           1  0
Anyoni Unative      1  0
Anyoni Unconary     1  0
Anyonon Coweboded   0  1
Anyonon Fruidy      0  1
Anyonon Pressive    1  0
Apench Flité        1  0
Apench Seen         0  1
Apench Ses          0  1
Apies Bun           1  0
Apies Pine          0  1
Apies Prity         0  1
Apix Clake          1  0
Apix Wala           2  0
Appers Vloaf        1  0
Appers Wala         0  1
Apple Cre           0  1
Apple Crité         1  0
Apple Kidne         1  0
Aps Hotte           0  1
Aps Raste           0  1
Aps Rhuba           1  0
Apsps Nutte         0  1
Apsps Terte         1  0
Aptal Binie         0  1
Aptal Chnik         0  1
Aptal Fate          1  0
Apuffs Facle        0  1
Arid Alcemblery     1  0
Arid Couresteer     0  1
Arid Idivent        0  1
Arin Fringh         1  0
Arin Prombled       1  0
Arino Gocent        0  1
Arino Slable        1  0
Arino Trupistic     0  1
Arinon Unkcal       0  1
Arion Quelfly       1  0
Ariton Mosteraked   1  0
Ariton Susent       0  1
Arix Dishocatal     0  1
Arix Oilloody       0  1
Arix Rentruing      0  1
Arkaban Coning      0  1
Arkaban Tertchty    0  1
Arkar Distured      1  0
Arkar Nifficaus     0  1
Arkard Mornaned     1  0
Arkard Secened      0  1
Arkard Sechausive   0  1
Arkeb Belstrut      0  1
Arl Chavezalez      1  0
Arl Lerez           1  0
Arl Oneidson        0  1
Arl Wagnerray       0  1
Arla Carterson      0  1
Arla Moodman        1  0
Arla Morelly        1  0
Arla Navages        0  1
Arla Sextones       0  1
Arlen Blacks        1  0
Arlen Jacostarks    0  1
Arlen Kellyons      1  0
Arlen Mclainez      0  1
Arlen Vincenton     0  1
Arlie Sweett        1  0
Arlie Woodwinez     1  0
Arllia Blainson     1  0
Arllia Ellahan      1  0
Arllia Hubbarrison  1  0
Arllia Mccarveymon  1  0
Arllia Mckinn       1  0
Arllia Nolds        0  1
Arllia Roachoanand  0  1
Arllia Sweenez      1  0
Armen Barkeretton   1  0
Armen Byerton       0  1
Armen Conleydenan   1  0
Armen Ellson        0  1
Armen Garnes        1  0
Armene Lewintos     0  1
Armene Patthews     0  1
Armene Sykess       1  0
Armene Vines        0  1
Armene Woodgezalez  1  0
Arrai Crantiale     1  0
Arrai Stracary      0  1
Arraiam Bealvewd    0  1
Arraiam Inghtal     0  1
Arraid Entenedy     0  1
Arraid Inicont      0  1
Arraid Opshaft      0  1
Arrain Chuble       0  1
Arrain Fordulgaug   0  1
Arrain Hednigic     0  1
Arrain Purellliss   1  0
Arrain Swingse      0  1
Arrak Fanchy        1  0
Ars Ches            1  0
Ars Cres            1  0
Ars Prity           0  1
Ars Shpie           0  1
Artis Beckeey       1  0
Artis Casonston     1  0
Artis Gambs         1  0
Artis Hanghanson    1  0
Artis Sancockett    1  0
Artis Weberton      0  1
Asch Meroliss       0  1
Asch Simous         0  1
Asch Stradick       1  1
Asellab Gocent      0  1
Asellah Dishocatal  0  1
Asellah Shricatory  0  1
Asellan Calved      0  1
Asellan Chocaters   1  0
Asellan Crueld      0  1
Asellan Fuelisent   0  1
Asellan Sprender    1  0
Asellan Taketiatim  1  0
Asellum Amblereld   0  1
Asellum Calazy      0  1
Asellum Colensid    1  0
Asellum Pringrous   1  0
Asellux Alaring     1  0
Asellux Assibler    1  0
Asellux Parbage     1  0
Ashelik Ainserfle   0  1
Ashelik Drayfulery  0  1
Ashir Frattyring    0  1
Ashir Mingious      0  1
Ashir Witeronfus    0  1
Ashira Stpingepid   0  1
Ashird Myling       0  1
Ashird Parbleake    1  0
Ashird Sorbitter    0  1