In [44]:
import pandas as pd
df = pd.read_csv("../resources/playground-series-s6e6/train.csv")

In [45]:
pd.set_option('display.max_columns', None)

In [46]:
df.head(5)

,id,alpha,delta,u,g,r,i,z,redshift,spectral_type,galaxy_population,class
0,0,147.734256,16.959273,25.472123,21.895559,20.357926,19.257113,18.621057,0.408982,M,Red_Sequence,GALAXY
1,1,127.988677,32.346716,20.778509,19.087062,17.587208,17.226067,16.786433,0.157976,M,Red_Sequence,GALAXY
2,2,179.792648,35.344843,21.035203,21.079128,21.171840,20.582629,20.557366,2.823770,O/B,Blue_Cloud,QSO
3,3,225.818295,48.569421,23.305056,21.050736,19.017754,18.365658,17.914952,0.536099,M,Red_Sequence,GALAXY
4,4,141.836135,19.342852,21.703158,19.471680,18.234449,17.899447,17.616185,0.555761,M,Red_Sequence,GALAXY

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 577347 entries, 0 to 577346
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 577347 non-null  int64
 1   alpha              577347 non-null  float64
 2   delta              577347 non-null  float64
 3   u                  577347 non-null  float64
 4   g                  577347 non-null  float64
 5   r                  577347 non-null  float64
 6   i                  577347 non-null  float64
 7   z                  577347 non-null  float64
 8   redshift           577347 non-null  float64
 9   spectral_type      577347 non-null  str
 10  galaxy_population  577347 non-null  str
 11  class              577347 non-null  str
dtypes: float64(8), int64(1), str(3)
memory usage: 52.9 MB

In [5]:
print(df.isnull().sum())

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [6]:
null_rows = df[df['CryoSleep'].isnull()]

In [7]:
null_rows

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
92,0099_02,Earth,NaN,G/12/P,TRAPPIST-1e,2.0,False,0.0,0.0,0.0,0.0,0.0,Thewis Connelson,True
98,0105_01,Earth,NaN,F/21/P,TRAPPIST-1e,27.0,False,0.0,0.0,570.0,2.0,131.0,Carry Cleachrand,False
104,0110_02,Europa,NaN,B/5/P,TRAPPIST-1e,40.0,False,0.0,331.0,0.0,0.0,1687.0,Aldeba Bootious,False
111,0115_01,Mars,NaN,F/24/P,TRAPPIST-1e,26.0,False,0.0,0.0,0.0,0.0,NaN,Rohs Pead,True
152,0173_01,Earth,NaN,E/11/S,TRAPPIST-1e,58.0,False,0.0,985.0,0.0,5.0,0.0,Hilip Grifford,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8620,9197_01,Europa,NaN,C/308/P,55 Cancri e,44.0,False,0.0,0.0,0.0,0.0,0.0,Bellus Platch,True
8651,9227_05,Earth,NaN,G/1498/P,TRAPPIST-1e,8.0,False,0.0,0.0,0.0,0.0,0.0,Hard Hinglendez,False
8664,9246_01,Earth,NaN,G/1490/S,TRAPPIST-1e,32.0,False,0.0,0.0,0.0,0.0,0.0,NaN,True
8675,9259_01,Earth,NaN,F/1893/P,TRAPPIST-1e,44.0,False,1030.0,1015.0,0.0,11.0,NaN,Annah Gilleyons,True
8687,9275_03,Europa,NaN,A/97/P,TRAPPIST-1e,30.0,False,0.0,3208.0,0.0,2.0,330.0,Atlasym Conable,True

In [8]:
df.corr(numeric_only=True)

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
Age,1.000000,0.068723,0.130421,0.033133,0.123970,0.101007,-0.075026
RoomService,0.068723,1.000000,-0.015889,0.054480,0.010080,-0.019581,-0.244611
FoodCourt,0.130421,-0.015889,1.000000,-0.014228,0.221891,0.227995,0.046566
ShoppingMall,0.033133,0.054480,-0.014228,1.000000,0.013879,-0.007322,0.010141
Spa,0.123970,0.010080,0.221891,0.013879,1.000000,0.153821,-0.221131
VRDeck,0.101007,-0.019581,0.227995,-0.007322,0.153821,1.000000,-0.207075
Transported,-0.075026,-0.244611,0.046566,0.010141,-0.221131,-0.207075,1.000000

In [47]:
df['class'].value_counts()

class
GALAXY    377480
QSO       117143
STAR       82724
Name: count, dtype: int64

In [10]:
df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,0
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,1
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,0
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,0
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,1

In [48]:
df.corr(numeric_only=True)['class']

KeyError: 'class'

In [12]:
non_numeric_cols = df.select_dtypes(exclude='number')

print(non_numeric_cols.nunique())

PassengerId    8693
HomePlanet        3
CryoSleep         2
Cabin          6560
Destination       3
VIP               2
Name           8473
dtype: int64

In [49]:
cat_cols = df.select_dtypes(include=['object', 'category']).columns
print(type(cat_cols))
#cat_cols = cat_cols.drop(['PassengerId', 'Name', 'Cabin'])
# Print the value counts for each categorical column
for col in cat_cols:
    print(f"--- Frequency Count for Column: {col} ---")
    print(df[col].value_counts())
    print("\n")

<class 'pandas.Index'>
--- Frequency Count for Column: spectral_type ---
spectral_type
M      303323
A/F    122122
G/K    108546
O/B     43356
Name: count, dtype: int64


--- Frequency Count for Column: galaxy_population ---
galaxy_population
Red_Sequence    319565
Blue_Cloud      257782
Name: count, dtype: int64


--- Frequency Count for Column: class ---
class
GALAXY    377480
QSO       117143
STAR       82724
Name: count, dtype: int64

/tmp/ipykernel_17570/324023460.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include=['object', 'category']).columns

In [14]:
pd.set_option('display.max_rows', None)

import numpy as np
(df['Age'].value_counts().sort_index())

Age
0.0     178
1.0      67
2.0      75
3.0      75
4.0      71
5.0      33
6.0      40
7.0      52
8.0      46
9.0      42
10.0     39
11.0     47
12.0     41
13.0    141
14.0    138
15.0    155
16.0    147
17.0    158
18.0    320
19.0    293
20.0    277
21.0    311
22.0    291
23.0    292
24.0    324
25.0    243
26.0    268
27.0    259
28.0    267
29.0    230
30.0    183
31.0    202
32.0    199
33.0    178
34.0    148
35.0    171
36.0    178
37.0    177
38.0    161
39.0    138
40.0    128
41.0    129
42.0    119
43.0    128
44.0    115
45.0     89
46.0     97
47.0     88
48.0     72
49.0     83
50.0     74
51.0     59
52.0     52
53.0     61
54.0     67
55.0     68
56.0     48
57.0     46
58.0     47
59.0     35
60.0     34
61.0     32
62.0     26
63.0     26
64.0     29
65.0     23
66.0      7
67.0     13
68.0     12
69.0      6
70.0      9
71.0      7
72.0      4
73.0      7
74.0      5
75.0      4
76.0      2
77.0      2
78.0      3
79.0      3
Name: count, dtype: int64

In [15]:
pd.crosstab(df['CryoSleep'], df['Transported'])

Transported     0     1
CryoSleep
False        3650  1789
True          554  2483