In [2]:
import pandas as pd

df = pd.read_csv("resources/playground-series-s4e9/train.csv")

pd.set_option('display.max_columns', None)

In [3]:
df.head(5)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  str
 2   model         188533 non-null  str
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     183450 non-null  str
 6   engine        188533 non-null  str
 7   transmission  188533 non-null  str
 8   ext_col       188533 non-null  str
 9   int_col       188533 non-null  str
 10  accident      186081 non-null  str
 11  clean_title   167114 non-null  str
 12  price         188533 non-null  int64
dtypes: int64(4), str(9)
memory usage: 18.7 MB

In [5]:
print(df.isnull().sum())

id                  0
brand               0
model               0
model_year          0
milage              0
fuel_type        5083
engine              0
transmission        0
ext_col             0
int_col             0
accident         2452
clean_title     21419
price               0
dtype: int64

In [18]:
# get a generic sense for if the rows look corrupted for NA values
null_rows = df[df['clean_title'].isnull()]
null_rows

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
20,20,Land,Rover Defender S,2023,7978,Gasoline,5.2L V10 40V PDI DOHC,8-Speed Automatic,Santorini Black Metallic,Black,None reported,NaN,41998
45,45,RAM,1500 Laramie,2022,27352,Gasoline,5.7L V8 16V MPFI OHV,8-Speed Automatic,Diamond Black,Black,None reported,NaN,42599
51,51,Tesla,Model 3 Long Range,2020,38360,NaN,Dual Motor - Standard,Automatic,White,Black,None reported,NaN,59598
60,60,Mercedes-Benz,GLS 450 Base 4MATIC,2017,44147,Gasoline,3.0L V6 24V GDI DOHC Twin Turbo,9-Speed Automatic,White,Parchment.,At least 1 accident or damage reported,NaN,29999
70,70,McLaren,570S Spider,2023,3254,Gasoline,3.8L V8 32V MPFI DOHC Twin Turbo,7-Speed Automatic with Auto-Shift,Vega Blue,Black,None reported,NaN,92500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188507,188507,Chevrolet,Corvette Stingray w/3LT,2023,3053,Gasoline,490.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Black,NaN,NaN,61999
188511,188511,Land,Rover Range Rover Velar P380 SE R-Dynamic,2022,15198,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Firenze Red,Ebony,None reported,NaN,23739
188513,188513,Lexus,GS 350 F Sport,2022,82046,Gasoline,3.5L V6 24V PDI DOHC,8-Speed Automatic,Caviar,Black,None reported,NaN,48990
188520,188520,Mercedes-Benz,GLC 300 GLC 300,2022,18031,Gasoline,2.0 Liter Turbo,Automatic,White,Black,None reported,NaN,39998
188531,188531,Audi,S5 3.0T Prestige,2022,13895,Gasoline,3.0L,1-Speed Automatic,Daytona Gray Pearl Effect,Black,None reported,NaN,84900

In [19]:
# how to replace null values?
print(df['clean_title'].nunique())
df['clean_title'].value_counts(dropna=False)

1

clean_title
Yes    167114
NaN     21419
Name: count, dtype: int64

In [21]:
df['fuel_type'].value_counts()

fuel_type
Gasoline          165940
Hybrid              6832
E85 Flex Fuel       5406
Diesel              3955
–                    781
Plug-In Hybrid       521
not supported         15
Name: count, dtype: int64

In [10]:
df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,0
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,1
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,0
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,0
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,1

In [48]:
df.corr(numeric_only=True)['class']

KeyError: 'class'

In [12]:
non_numeric_cols = df.select_dtypes(exclude='number')

print(non_numeric_cols.nunique())

PassengerId    8693
HomePlanet        3
CryoSleep         2
Cabin          6560
Destination       3
VIP               2
Name           8473
dtype: int64

In [49]:
cat_cols = df.select_dtypes(include=['object', 'category']).columns
print(type(cat_cols))
#cat_cols = cat_cols.drop(['PassengerId', 'Name', 'Cabin'])
# Print the value counts for each categorical column
for col in cat_cols:
    print(f"--- Frequency Count for Column: {col} ---")
    print(df[col].value_counts())
    print("\n")

<class 'pandas.Index'>
--- Frequency Count for Column: spectral_type ---
spectral_type
M      303323
A/F    122122
G/K    108546
O/B     43356
Name: count, dtype: int64


--- Frequency Count for Column: galaxy_population ---
galaxy_population
Red_Sequence    319565
Blue_Cloud      257782
Name: count, dtype: int64


--- Frequency Count for Column: class ---
class
GALAXY    377480
QSO       117143
STAR       82724
Name: count, dtype: int64

/tmp/ipykernel_17570/324023460.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include=['object', 'category']).columns

In [14]:
pd.set_option('display.max_rows', None)

import numpy as np
(df['Age'].value_counts().sort_index())

Age
0.0     178
1.0      67
2.0      75
3.0      75
4.0      71
5.0      33
6.0      40
7.0      52
8.0      46
9.0      42
10.0     39
11.0     47
12.0     41
13.0    141
14.0    138
15.0    155
16.0    147
17.0    158
18.0    320
19.0    293
20.0    277
21.0    311
22.0    291
23.0    292
24.0    324
25.0    243
26.0    268
27.0    259
28.0    267
29.0    230
30.0    183
31.0    202
32.0    199
33.0    178
34.0    148
35.0    171
36.0    178
37.0    177
38.0    161
39.0    138
40.0    128
41.0    129
42.0    119
43.0    128
44.0    115
45.0     89
46.0     97
47.0     88
48.0     72
49.0     83
50.0     74
51.0     59
52.0     52
53.0     61
54.0     67
55.0     68
56.0     48
57.0     46
58.0     47
59.0     35
60.0     34
61.0     32
62.0     26
63.0     26
64.0     29
65.0     23
66.0      7
67.0     13
68.0     12
69.0      6
70.0      9
71.0      7
72.0      4
73.0      7
74.0      5
75.0      4
76.0      2
77.0      2
78.0      3
79.0      3
Name: count, dtype: int64

In [15]:
pd.crosstab(df['CryoSleep'], df['Transported'])

Transported     0     1
CryoSleep
False        3650  1789
True          554  2483